# Generated by Django 5.2 on 2025-04-29 14:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('faturamento_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('interesse', models.CharField(choices=[('consorcio', 'Consórcio'), ('carta_credito', 'Carta de Crédito'), ('capital_giro', 'Capital de Giro'), ('financiamento', 'Financiamento'), ('emprestimo', 'Empréstimo'), ('outro', 'Outro')], default='consorcio', max_length=20)),
                ('valor_interesse', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de interesse')),
                ('prazo_desejado', models.IntegerField(blank=True, null=True, verbose_name='Prazo desejado (meses)')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('contatado', 'Contatado'), ('qualificado', 'Qualificado'), ('proposta', 'Proposta Enviada'), ('negociacao', 'Em Negociação'), ('fechado', 'Fechado'), ('perdido', 'Perdido')], default='novo', max_length=20)),
                ('fonte', models.CharField(choices=[('site', 'Website'), ('indicacao', 'Indicação'), ('redes_sociais', 'Redes Sociais'), ('ligacao', 'Ligação Direta'), ('email', 'Email Marketing'), ('evento', 'Evento'), ('parceiro', 'Parceiro'), ('importacao', 'Importação de Arquivo'), ('outro', 'Outro')], default='site', max_length=20, verbose_name='Fonte')),
                ('prioridade', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], default=2)),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='Última modificação')),
                ('data_ultimo_contato', models.DateTimeField(blank=True, null=True, verbose_name='Data do último contato')),
                ('data_proxima_acao', models.DateTimeField(blank=True, null=True, verbose_name='Data da próxima ação')),
                ('arquivo_origem', models.CharField(blank=True, max_length=255, null=True, verbose_name='Arquivo de origem')),
                ('importado_em', models.DateTimeField(blank=True, null=True, verbose_name='Importado em')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
