# Generated by Django 5.2 on 2025-04-29 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativaContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.CharField(choices=[('sucesso', 'Contato realizado com sucesso'), ('nao_atendeu', 'Não atendeu'), ('ocupado', 'Ocupado/Indisponível'), ('numero_invalido', 'Número inválido'), ('outro', 'Outro motivo')], default='nao_atendeu', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas_contato', to='leads.lead')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas_contato', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tentativa de contato',
                'verbose_name_plural': 'Tentativas de contato',
                'ordering': ['-data_hora'],
            },
        ),
    ]
