# Generated by Django 5.2 on 2025-05-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0002_evento_nota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['-prioridade', '-data_criacao'], 'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='concluida',
            new_name='concluido',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='data_lembrete',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='tipo',
        ),
        migrations.AddField(
            model_name='evento',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('reuniao', 'Reunião'), ('prazo', 'Prazo/Deadline'), ('contato', 'Contato com Lead'), ('outro', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='nota',
            name='prioridade',
            field=models.IntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], default=2),
        ),
    ]
