# Generated by Django 5.2 on 2025-05-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0003_alter_nota_options_rename_concluida_nota_concluido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='tipo',
            field=models.CharField(choices=[('nota', 'Nota'), ('lembrete', 'Lembrete')], default='nota', max_length=20),
        ),
    ]
