# Generated by Django 5.2 on 2025-05-26 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0002_comunicacao_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('demografico', 'Demográfico'), ('comportamental', 'Comportamental'), ('engajamento', 'Engajamento'), ('interesse', 'Interesse')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('pontos', models.IntegerField(default=0)),
                ('condicao', models.TextField(help_text='Condição em formato JSON para avaliação automática')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Critério de Pontuação',
                'verbose_name_plural': 'Critérios de Pontuação',
            },
        ),
        migrations.CreateModel(
            name='GatilhoAutomatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('evento', models.CharField(choices=[('lead_criado', 'Lead Criado'), ('contato_realizado', 'Contato Realizado'), ('status_alterado', 'Status do Lead Alterado'), ('sem_atividade', 'Sem Atividade há X dias'), ('score_threshold', 'Score Atingiu Threshold'), ('data_vencimento', 'Data de Vencimento'), ('email_aberto', 'E-mail Aberto'), ('link_clicado', 'Link Clicado')], max_length=20)),
                ('condicoes', models.TextField(help_text='Condições em formato JSON para ativação do gatilho')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gatilho Automático',
                'verbose_name_plural': 'Gatilhos Automáticos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='CampanhaNutricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('objetivo', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('pausada', 'Pausada'), ('concluida', 'Concluída'), ('rascunho', 'Rascunho')], default='rascunho', max_length=20)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criterios_segmentacao', models.TextField(blank=True, help_text='Critérios para incluir leads na campanha (JSON)')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campanha de Nutrição',
                'verbose_name_plural': 'Campanhas de Nutrição',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='EtapaCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('tarefa', 'Tarefa para Vendedor'), ('aguardar', 'Aguardar')], max_length=20)),
                ('delay_dias', models.IntegerField(default=0, help_text='Dias após a etapa anterior')),
                ('assunto', models.CharField(blank=True, max_length=500)),
                ('conteudo', models.TextField(blank=True)),
                ('condicoes', models.TextField(blank=True, help_text='Condições para executar esta etapa (JSON)')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='automacao.campanhanutricao')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.templateemail')),
                ('template_whatsapp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.templatewhatsapp')),
            ],
            options={
                'verbose_name': 'Etapa da Campanha',
                'verbose_name_plural': 'Etapas das Campanhas',
                'ordering': ['campanha', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='LeadScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao_total', models.IntegerField(default=0)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('pontos_demograficos', models.IntegerField(default=0)),
                ('pontos_comportamentais', models.IntegerField(default=0)),
                ('pontos_engajamento', models.IntegerField(default=0)),
                ('pontos_interesse', models.IntegerField(default=0)),
                ('classificacao', models.CharField(choices=[('frio', 'Lead Frio (0-30)'), ('morno', 'Lead Morno (31-60)'), ('quente', 'Lead Quente (61-80)'), ('muito_quente', 'Lead Muito Quente (81-100)')], default='frio', max_length=20)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Pontuação de Lead',
                'verbose_name_plural': 'Pontuações de Leads',
                'ordering': ['-pontuacao_total'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('trigger', models.CharField(choices=[('lead_criado', 'Lead Criado'), ('status_alterado', 'Status Alterado'), ('sem_contato', 'Sem Contato por X dias'), ('score_alterado', 'Score Alterado'), ('data_especifica', 'Data Específica'), ('acao_manual', 'Ação Manual')], max_length=20)),
                ('condicoes', models.TextField(blank=True, help_text='Condições em formato JSON para execução do workflow')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoAutomacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('workflow', 'Workflow'), ('campanha', 'Campanha de Nutrição'), ('gatilho', 'Gatilho Automático'), ('score', 'Atualização de Score')], max_length=20)),
                ('acao', models.CharField(max_length=200)),
                ('detalhes', models.TextField(blank=True)),
                ('sucesso', models.BooleanField(default=True)),
                ('data_execucao', models.DateTimeField(auto_now_add=True)),
                ('campanha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automacao.campanhanutricao')),
                ('gatilho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automacao.gatilhoautomatico')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automacao.workflow')),
            ],
            options={
                'verbose_name': 'Histórico de Automação',
                'verbose_name_plural': 'Histórico de Automações',
                'ordering': ['-data_execucao'],
            },
        ),
        migrations.AddField(
            model_name='gatilhoautomatico',
            name='workflow',
            field=models.ForeignKey(help_text='Workflow a ser executado quando o gatilho for ativado', on_delete=django.db.models.deletion.CASCADE, to='automacao.workflow'),
        ),
        migrations.CreateModel(
            name='ExecucaoWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('executando', 'Executando'), ('concluido', 'Concluído'), ('erro', 'Erro'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('data_proxima_acao', models.DateTimeField(blank=True, null=True)),
                ('acao_atual', models.IntegerField(default=1)),
                ('log_execucao', models.TextField(blank=True)),
                ('erro_detalhes', models.TextField(blank=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automacao.workflow')),
            ],
            options={
                'verbose_name': 'Execução de Workflow',
                'verbose_name_plural': 'Execuções de Workflows',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AcaoWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(default=1)),
                ('tipo_acao', models.CharField(choices=[('enviar_email', 'Enviar E-mail'), ('enviar_whatsapp', 'Enviar WhatsApp'), ('criar_tarefa', 'Criar Tarefa'), ('alterar_status', 'Alterar Status'), ('atribuir_vendedor', 'Atribuir Vendedor'), ('aguardar', 'Aguardar X dias'), ('notificar_usuario', 'Notificar Usuário')], max_length=20)),
                ('parametros', models.TextField(help_text='Parâmetros da ação em formato JSON')),
                ('delay_dias', models.IntegerField(default=0, help_text='Delay em dias antes de executar esta ação')),
                ('condicoes', models.TextField(blank=True, help_text='Condições específicas para esta ação')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='automacao.workflow')),
            ],
            options={
                'verbose_name': 'Ação do Workflow',
                'verbose_name_plural': 'Ações dos Workflows',
                'ordering': ['workflow', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='ParticipacaoCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('pausada', 'Pausada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='ativa', max_length=20)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('etapa_atual', models.IntegerField(default=1)),
                ('data_proxima_etapa', models.DateTimeField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automacao.campanhanutricao')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
            options={
                'verbose_name': 'Participação em Campanha',
                'verbose_name_plural': 'Participações em Campanhas',
                'ordering': ['-data_entrada'],
                'unique_together': {('campanha', 'lead')},
            },
        ),
    ]
